RESOURCE_WAITING_FOR_APPROVAL = 1
RESOURCE_APPROVED = 2
RESOURCE_REJECTED = 3
RESOURCES_STATUSES = [
    (RESOURCE_WAITING_FOR_APPROVAL, 'Waiting for approval',),
    (RESOURCE_APPROVED, 'Approved',),
    (RESOURCE_REJECTED, 'Rejected',),
]
