# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_organisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisations',
            field=models.ManyToManyField(blank=True, to='directory.Organisation'),
        ),
    ]
