# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('accounts', '0004_organisations_remove_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organisations',
        ),
        migrations.AddField(
            model_name='user',
            name='approved_organisations',
            field=models.ManyToManyField(blank=True, related_name='approved_organisations', to='directory.Organisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='chosen_organisations',
            field=models.ManyToManyField(blank=True, help_text='Organisations chosen on the registration.', to='directory.Organisation'),
        ),
    ]
