# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 10:08
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('abstract', models.TextField(help_text='This text will appear in search results', max_length=140)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='uploads/resources/images/%Y/%m/%d', verbose_name='Background Image')),
                ('is_approved', models.BooleanField(default=False)),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='How many times page been hit?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_created', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='resources_likes', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(help_text='Of the groups you belong to, which one owns this resource?', on_delete=django.db.models.deletion.CASCADE, to='directory.Organisation')),
                ('privacy', models.ManyToManyField(blank=True, help_text='Of the groups you belong to, which should this resource be visible to?', related_name='resources_privacy', to='directory.Organisation')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
                ('tried', models.ManyToManyField(blank=True, related_name='resources_tried', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
