# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
