# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_change_crated_at_default_to_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting for approval'), (2, 'Approved'), (3, 'Rejected')], default=1),
        ),
    ]
