# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_change_content_field_for_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
