# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-30 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_change_slug_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Resource categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ResourceCategoryFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_featured_resources', to='resources.ResourceCategory')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource')),
            ],
            options={
                'verbose_name': 'Featured Resource',
                'ordering': ['project_order'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ManyToManyField(to='resources.ResourceCategory'),
        ),
    ]
