# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-02 13:37
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_add_resource_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to='uploads/resources/categories/images/%Y/%m/%d', verbose_name='Lead category image'),
            preserve_default=False,
        ),
    ]
