# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 14:07
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_organisation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='uploads/directory/organisation/%Y/%m/%d'),
        ),
    ]
