# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_change_imagefield_to_sorl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
