# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 11:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_change_created_at_to_default_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
