# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_change_field_upload_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='founder',
            field=models.BooleanField(default=False),
        ),
    ]
