# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_organisation_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, help_text='This email helps to get auto access for the users with the same email domain', max_length=254),
        ),
    ]
