# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-06-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_add_help_text_for_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='show_logo_on_footer',
            field=models.BooleanField(default=True),
        ),
    ]
