# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-06-28 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_organisation_show_logo_on_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo_sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='The organisation logos with the higher numbers are showed first from the left'),
        ),
    ]
