# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
    ]
